### PR TITLE
Set default value {} in cloud_properties_json column

### PR DESCRIPTION
**Pull request by mattcui**
Submitted this PR to address [issue 1133](https://github.com/cloudfoundry/bosh/issues/1133), I already verified this change, I can see the default value "{}" set in the  newly added column cloud_properties_json.

 id | instance_id | disk_cid |  size  | active | cloud_properties_json
----+-------------+----------+--------+--------+-----------------------
  1 |           2 | 8091253  | 524288 | t      | {}
  2 |           4 | 8091423  | 153600 | t      | {}

### CODE REVIEW

**Comment by mattcui** [comment]
Travis-ci failed, it should not be a problem in my change, the same failure occurred in the previous [PR
1134](https://github.com/cloudfoundry/bosh/pull/1134)
https://travis-ci.org/cloudfoundry/bosh/builds/109647679

**Comment by bosh-ci-push-pull** [comment]
you ll have create a new migration since once migration is published it cannot be modified. 

please also add a test for the migration to make sure we dont override existing data (eg https://github.com/cloudfoundry/bosh/tree/master/bosh-director/spec/unit/db)

**Comment by mattcui** [comment]
@bosh-ci-push-pull 
I just need to replicate the content of 20141204234517_add_cloud_properties_to_persistent_disk.rb to a new file, or I should assume the column cloud_properties_json is already added by 20141204234517_add_cloud_properties_to_persistent_disk.rb, in my code, I just need to set {} if the value is "" (nil) in the column? Thanks.

**Comment by cppforlife** [comment]
@mattcui it's already added. this is a new migration from the current (latest) db schema to whatever the new default is.

**Comment by mattcui** [comment]
@cppforlife Seems test cases operating on the same database are polluted by each other, after adding my db migration and unit test, the unit test for "AttachDisk" always failed, you can see the error in the [travis log](https://travis-ci.org/cloudfoundry/bosh/builds/113596086). I remember it failed even I removed my test case (still retain migration db script). Do you have any idea on how to fix that? Thanks.

@maximilien

**Comment by cppforlife** [comment]
@mattcui Update looks good. We'll pull it in for the next release.

**Comment by cppforlife** [comment]
Story: https://www.pivotaltracker.com/story/show/115721221

**Comment by wlindner** [comment]
Thanks for the PR - we gave it a look and started to merge, but noticed a couple issues when running the full test suites...

* The travis failure above is due to unit test environment. We fixed it with the following if you want to apply the patch:
```
diff --git a/bosh-director/spec/unit/jobs/attach_disk_spec.rb b/bosh-director/spec/unit/jobs/attach_disk_spec.rb
index a01a363..adf21b6 100644
--- a/bosh-director/spec/unit/jobs/attach_disk_spec.rb
+++ b/bosh-director/spec/unit/jobs/attach_disk_spec.rb
@@ -62,7 +62,7 @@ module Bosh::Director

         it 'marks the pre existing active persistent disk as inactive and orphans it' do
           attach_disk_job.perform
-          expect(instance_model.persistent_disks).to_not include(original_disk)
+          expect(instance_model.persistent_disks[0].disk_cid).to eq('fake_disk_cid')
           original_persistent_disk = Models::PersistentDisk[disk_cid: 'original-disk-cid']
           expect(original_persistent_disk).to be(nil)
```

* This new defaulting of fields within the database does not work in MySQL (it doesn't seem to support defaults of `TEXT` fields which the `cloud_properties_json` uses). We get the following error.
```
BLOB/TEXT column 'cloud_properties_json' can't have a default value (Sequel::DatabaseError)
```

If you're still interested in this PR being merged, please have a look and resolve those issues and then let us know once they have been pushed. Then we can take another look at merging. Thanks!

**Comment by dpb587-pivotal** [comment]
Closing - if you're still interested in seeing these changes, please feel free to take another look at the feedback and reopen with changes. I'm guessing that by now most migrations have happened and this is much less of an issue.

**Comment by maximilien** [comment]
@dpb587 are you saying this was never pulled in?

**Comment by dpb587-pivotal** [comment]
Correct; and I don't see any similar or equivalent changes in the repo.

**Comment by maximilien** [comment]
@mattcui can you chime in here and confirm we are good on this front. Thx

**Comment by mattcui** [comment]
@maximilien We added it in our forked BOSH v1 release, I don't think there is the problem when migrating from BOSH v1 to v2 without this commit, not sure about the case from legacy BOSH to BOSH v2, but we should have no such case. So, I think it's OK to close it with unmerged.

**Pull request closed without merging**
