### PR TITLE
[Power Support] Update build configuration files to support IBM Power platform (for ruby and libpq packages)

### PR DESCRIPTION
**Pull request by allomov**
This PR is made to provide IBM Power support to BOSH.

You can find details of the issue in this PR https://github.com/cloudfoundry/bosh/pull/892. I've come to the idea of this changes thanking to Matthew Sykes (and his post in [cf-dev](http://lists.cloudfoundry.org/pipermail/cf-dev/2015-July/000911.html)).

### CODE REVIEW

**Comment by cppforlife** [comment]
Hey @allomov. We typically want to avoid usage of pre_packaging scripts (since they run in a deterministic environment) and requiring internet access. For this PR it should be really simple to resolve it. Just commit files being downloaded into the src directory and then replace config files in the appropriate `packaging` scripts if ppc64le.

**Comment by allomov** [comment]
@cppforlife I fully agree with you about using `pre_packaging` scripts. I used `pre_packaging` script to  show you the source of `config.guess` file. Also I was not sure about where to place `config.guess` file. Is it ok to place it to `src/common/config.guess`?

**Comment by cppforlife** [comment]
I would just create `src/config/config.guess` and `src/config/config.sub`.

**Comment by allomov** [comment]
Ok. Thank you for advise.

**Pull request closed without merging**
