### PR TITLE
Make Azure Cloud configurable for director blobstore

### PR DESCRIPTION
**Pull request by s4heid**
### What is this change about?

This change introduces a configuration option for the director blobstore that supports storage accounts on non-public Azure Clouds.

### Please provide contextual information.

#2544

### What tests have you run against this PR?

Deployed a director including these changes on AzureChinaCloud, replaced the bosh-azure-storage-cli with one that includes https://github.com/cloudfoundry/bosh-azure-storage-cli/pull/16, and validated that issue #2544 is resolved.

### How should this change be described in bosh release notes?

To enable configuration of the BOSH Director blobstore in different Azure Clouds, a new parameter `environment` has been introduced. Users can specify the desired Azure Cloud environment (e.g., AzureUSGovernment, AzureChinaCloud) using the environment parameter in their BOSH Director configuration.

### Does this PR introduce a breaking change?

No.

### Tag your pair, your PM, and/or team!

@jpalermo, @a-hassanin

### CODE REVIEW

**Comment by jpalermo** [comment]
Maybe `blobstore.azure_environment` rather than `blobstore.environment` to make it more clear it's only for Azure?

**Review by aramprice — APPROVED** [review]
This addition looks reasonable, thanks!

**Review by jpalermo — CHANGES_REQUESTED** [review]
Moving this into a proper "review"

Maybe `blobstore.azure_environment` rather than `blobstore.environment` to make it more clear it's only for Azure?

**Comment by s4heid** [comment]
Highlighting the IaaS aspect is a good call.  Additionally, it's worth noting that within the Azure CLI, this attribute is referred to as AZURE_CLOUD_NAME, whereas in the bosh-azure-cpi, it's termed as 'environment', where the IaaS context is more apparent.  I'm comfortable with either naming convention, be it azure_cloud_name or azure_environment. @jpalermo  feel free to choose whichever you prefer, and I'll adjust the PR.

**Comment by jpalermo** [comment]
Lets keep it closer to the azure cli convention, hopefully that makes it make more sense for future contributors and users.

**Comment by s4heid** [comment]
@jpalermo sounds reasonable. I adapted the pull request.

**Review by beyhan — APPROVED** [review]

**Comment by beyhan** [comment]
@s4heid could you please resolve the conflicts so that we can merge this.

**Comment by s4heid** [comment]
sorry for the delay, I was travelling. seems like joseph already took care - thanks! :)

**Pull request merged**
