### PR TITLE
validate_db_connection

### PR DESCRIPTION
**Pull request by ronakbanka**
Abstract : To validate the db connection because once the director-worker is spawned by the monit , if there is a connection break on postgres DB side then this thread gives a Error i.e not able to connect PG error and no worker Job is processed (create release , delete release).

Solution: Using connection validator extension from sequel , if there is a persistent connection then all things are fine but if connection breaks this extension will validate the connection and worker will process the job.

By default the timeout is 3600 ( 1 hour ) but can reduce in cases where either firewall or other network issues we are loosing connections to database.

Below is error trace:

 INFO  DirectorWorker : got: (Job{normal} | Bosh::Director::Jobs::DeleteRelease | [10, "pgpool", {"version"=>nil}])
 INFO  DirectorWorker : Running before_fork hooks with [(Job{normal} | Bosh::Director::Jobs::DeleteRelease | [10, "pgpool", {"version"=>nil}])]
 INFO  DirectorWorker : Running after_fork hooks with [(Job{normal} | Bosh::Director::Jobs::DeleteRelease | [10, "pgpool", {"version"=>nil}])]
 INFO  DirectorWorker : (Job{normal} | Bosh::Director::Jobs::DeleteRelease | [10, "pgpool", {"version"=>nil}]) failed: #<Sequel::DatabaseDisconnectError: PG::Error: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
>
 INFO  DirectorWorker : /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:145:in `exec'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/database/logging.rb:37:in `log_yield'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:132:in `block in execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:111:in `check_disconnect_errors'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:132:in `execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:413:in `_execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:242:in `block (2 levels) in execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:425:in `check_database_errors'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:242:in `block in execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/database/connecting.rb:236:in `synchronize'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:242:in `execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/dataset/actions.rb:801:in `execute'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/adapters/postgres.rb:525:in `fetch_rows'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/model/base.rb:798:in `primary_key_lookup'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/sequel-3.43.0/lib/sequel/model/base.rb:117:in `[]'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2780.0/lib/bosh/director/api/task_manager.rb:11:in `find_task'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2780.0/lib/bosh/director/job_runner.rb:21:in `initialize'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2780.0/lib/bosh/director/jobs/base_job.rb:10:in `new'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2780.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'

### CODE REVIEW

**Comment by cppforlife** [comment]
@ronakbanka Nice! We'll pull this in.

> By default the timeout is 3600 ( 1 hour ) but can reduce in cases where either firewall or other network issues we are loosing connections to database.

What are you guys setting the timeout to in your environment?

**Comment by ronakbanka** [comment]
@cppforlife In our Environment we are using much lower timeout of 150 . I used 150 just keeping in mind some release operation on db side. 
But my main reason to put 3600 as default is most people don't face a db connection break if they are using a dedicated database. We are using a Postgres HA cluster.

**Comment by shinji62** [comment]
Yes basicaly we created a pgpool release, to make postgres HA and so on.

**Comment by frodenas** [comment]
@shinji62 OSS it or doesn't exists! :)

**Comment by ronakbanka** [comment]
@frodenas sure We will do it  :)

**Comment by frodenas** [comment]
@ronakbanka Awesome! Thanks!

**Comment by shinji62** [comment]
@frodenas ah ah ah ! Yes we will OSS it, just need some cleanup and more testing !

**Comment by cppforlife** [comment]
@shinji62 that sounds awesome. very exciting.

**Comment by ronakbanka** [comment]
@cppforlife Hi should I open a issue request for the same to add it to tracker story or just this PR is enough?

**Comment by bosh-ci-push-pull** [comment]
I've actually already prioritized this PR in the backlog:
https://www.pivotaltracker.com/story/show/88572280

**Comment by cppforlife** [comment]
Merged first iteration that solves for non-RDS DBs. https://github.com/cloudfoundry/bosh/commit/f41407635c4818bd41f050f5ebec70a82ad2d379

**Comment by ronakbanka** [comment]
Thanks @cppforlife

**Pull request closed without merging**
