### PR TITLE
support instance tags and include relevant specs

### PR DESCRIPTION
**Pull request by anshrupani**
### What is this change about?

The change allows to configure instance group specific tags, by allowing the user to include tags under <instance_group> -> env -> bosh -> tags in the manifest.

These tags can be configured as follows:
```
instance_groups:
- name: <instance_group>
  env:
    bosh:
     .
     .
      tags:
        tag1: value1
        tag2: value2
```
The deployment tags and the tags from the runtime config are also merged.

These tags can be useful under many circumstances, for example, in a large organisation, it makes identifying teams responsible for different instances easier. Also, This feature removes the necessity of including tags for the entire deployment when such tags aren't needed for all the involved instance groups. 
### What tests have you run against this PR?

bosh-director unit tests, dev-release testing on development environments

### How should this change be described in bosh release notes?

Support instance group specific tags.

### Does this PR introduce a breaking change?

No breaking change, since this PR just supports additional functionality of supporting instance tags.

### Tag your pair, your PM, and/or team!
@mvach @a-hassanin

### CODE REVIEW

**Comment by beyhan** [comment]
@ansh-SAP could you please sign the CLI and also add information about why this change is useful.

**Comment by anshrupani** [comment]
> @anshrupani one of the commits is with @ansh-SAP which didn't sign the CLA. Could you fix this and also add information about why this change is useful.

Thanks for pointing out!

**Comment by ramonskie** [comment]
could you squash these commits?

**Review by rkoster — CHANGES_REQUESTED** [review]
The feature makes sense but why was added under `bosh.env` instead of added as a instance-level key:
```yaml
instance_groups:
- name: foo
  tags:
    bar: foo
```

Furthermore I think it would be better to add this logic somewhere in the deployment_plan, for example in: [src/bosh-director/lib/bosh/director/deployment_plan/instance_plan_factory.rb](https://github.com/cloudfoundry/bosh/blob/main/src/bosh-director/lib/bosh/director/deployment_plan/instance_plan_factory.rb) (but maybe you find a better place, but this looked fairly close).

Last but not least I would expect some tests which exercise the new code paths.

**Comment by rkoster** [comment]
Closing in favour of https://github.com/cloudfoundry/bosh/pull/2448

**Pull request closed without merging**
