### PR TITLE
bosh events command should show deployment events

### PR DESCRIPTION
**Pull request by barthy1**
Event records contain:
-  name of the deployment
-  action (create, update, delete)
-  state of the action started/done/error/cancelled
-  error message if exists
-  task id
-  timestamp

[#112797557](https://www.pivotaltracker.com/story/show/112797557)

Signed-off-by: Peter Kalambet <peter.kalambet@ru.ibm.com>

### CODE REVIEW

**Comment by barthy1** [comment]
Previous PR has the same CI failure as this one. Perhaps problem is not in the code?

**Comment by allomov** [comment]
@barthy1 I had the same problem with CI. I think you should ping someone from BOSH team to re-run tests.

**Comment by bosh-ci-push-pull** [comment]
Don't worry about the Travis failures if it's not applicable. We'll run the
tests on concourse before merging. I'll add a chore to the backlog to
investigate these failures.

**Comment by tylerschultz** [comment]
FYI - I've fixed the test that was failing on Travis. Future Travis runs should work correctly.

**Pull request merged**
