### PR TITLE
Check for errors in unpacking packages during upload release.

### LINKED ISSUE #1274: Uploading a release with low disk space returns a checksum error
We get the following error when we try to upload a large release with low disk space:

```
Verifying manifest...
Extract manifest                                             OK
Manifest exists                                              OK
Release name/version                                         OK

File exists and readable                                     OK
Read package "some-package' (1 of 8)                               OK
Package 'some-package' checksum                                    OK
Read package 'some-package-1' (2 of 8)                            OK
Package 'some-package-1' checksum                                OK
Read package 'some-package-2' (3 of 8)                            OK
Package 'some-package-2' checksum                                FAILED
Read package 'some-package-3' (4 of 8)                           OK
Package 'some-package-3' checksum                                FAILED
Read package 'some-package-4' (5 of 8)                            OK
Package 'some-package-4' checksum                                FAILED
Read package 'some-package-5' (6 of 8)                           OK
Package 'some-package-5' checksum                               FAILED
Read package 'some-package-6' (7 of 8)                           OK
Package 'some-package-6' checksum                               FAILED
Read package 'some-package-7' (8 of 8)                            OK
Package 'some-package-7' checksum                                 FAILED
Package dependencies                                         OK
Checking jobs format                                         OK
```

Expected: Error out when fail to unpack

Actual: No error indicating unpack failed, instead check sum error.

Possible solution: Check the status when unpacking the packages: https://github.com/cloudfoundry/bosh/blob/695bed549bd93dd263285b6da08b4c23fe24e98c/bosh_cli/lib/cli/release_tarball.rb#L270

### PR DESCRIPTION
**Pull request by Petahhh**
Closes #1274 (https://github.com/cloudfoundry/bosh/issues/1274)
Signed-off-by: Peter Tran ptran@pivotal.io

### CODE REVIEW

**Comment by dpb587-pivotal** [comment]
For merger...

 * reminder this was PR'd against master instead of develop; merge manually
 * unit tests (2.3.1/sqlite) were green when merged with develop at 7fffa21ddb99af510fda0aa62dbc3f2da0133077

**Comment by cunnie** [comment]
Hi @Petahhh , 

Let me know when you've signed the CLA, thanks.

**Comment by Petahhh** [comment]
@cunnie I have it signed. Should I fax it in?

**Comment by Petahhh** [comment]
Hi @cunnie, what can I do to help move this along? Thank you!

**Comment by cppforlife** [comment]
@Petahhh it's in the queue to be pulled in.

**Comment by cppforlife** [comment]
CLI v2 (https://github.com/cloudfoundry/bosh-cli) covers this scenario in a more holistic manner. Putting this PR on freeze as we are migrating towards v2.

**Comment by cunnie** [comment]
@Petahhh I apologize for not getting back to you -- this one slipped through the cracks. I'll try to be more responsive to PRs in the future.

**Pull request closed without merging**
