### PR TITLE
Add arbitrary metadata tags to deploy manifest.

### PR DESCRIPTION
**Pull request by jmcarp**
This is a first pass at the interface described by @cppforlife in https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/issues/33#issuecomment-223487970. I'm not very familiar with the bosh internals, so let me know if there's a better way to do this, and I'll be happy to revise.

[Resolves https://github.com/cloudfoundry/bosh/issues/936]
[Resolves https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/issues/33]

### CODE REVIEW

**Comment by cppforlife** [comment]
@jmcarp any reason why we need to save tags into db? we already save entire manifest so might as well read it off from there? wdyt?

**Comment by jmcarp** [comment]
Makes sense to me--do you mean something like:

```ruby
manifest = YAML.load(instance.deployment.manifest || '{}')
metadata = metadata.merge(manifest.fetch('tags', {}))
```

or

```ruby
manifest = Manifest.load_from_model(instance.deployment)
metadata = metadata.merge(manifest.to_hash.fetch('tags', {}))
```

If we read the tags from the manifest in `VmMetadataUpdater`, then can we also drop the changed to `DeploymentSpecParser`? I added those based on discussion in https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/issues/33#issuecomment-223487970, and my impression was that the purpose of parsing tags in `DeploymentSpecParser` would be to add them as a new field to the `Deployment` model.

**Comment by jmcarp** [comment]
@cppforlife: does the snippet above make sense? If so, I'll revise the patch so that tags aren't stored in the database or parsed in `DeploymentSpecParser`.

**Comment by cppforlife** [comment]
@jmcarp looks about right. have to guard against empty string or null i think.

**Comment by jmcarp** [comment]
@cppforlife: OK, updated to read tags from the manifest instead of saving to the db.

**Comment by jmcarp** [comment]
Ping @cppforlife. Is this closer to what you had in mind?

**Comment by cppforlife** [comment]
@jmcarp we are pulling this in and rearranging some tests/implementations.

**Comment by dpb587-pivotal** [comment]
Related story: https://www.pivotaltracker.com/story/show/129890801

**Comment by jmcarp** [comment]
Interesting, looks like you all switched back to the implementation I was working with originally, when tags were parsed and stored in their own model: https://github.com/cloudfoundry/bosh/commit/06eb96835d3928cdc13bedece1c7a9902d3ff604.

**Comment by jmcarp** [comment]
For reference, old work at https://github.com/jmcarp/bosh/commit/d0987072ed9544f68234c67096e549602f17dc28.

**Comment by cppforlife** [comment]
@jmcarp misunderstanding on their part, we are doing what you did in memory. code coming shortly with additional tests.

**Comment by cppforlife** [comment]
I think this was delivered in v258 release.

**Comment by cppforlife** [comment]
Thanks for getting the ball rolling on this.

**Pull request closed without merging**
