### PR TITLE
Bump ruby version to 3.1.2

### PR DESCRIPTION
**Pull request by ShilpaChandrashekara**
Co-authored-by: Aadesh Misra <aadesh.misra@sap.com>

### What is this change about?

Bump ruby from 3.1.0 to 3.1.2

### Please provide contextual information.

Security scans recommends to update ruby gem from 3.3.3 to 3.3.10.

### What tests have you run against this PR?

Unit Tests

### How should this change be described in bosh release notes?

Bump ruby from 3.1.0 to 3.1.2

### Tag your pair, your PM, and/or team!
@aadeshmisra
@friegger

### CODE REVIEW

**Comment by ShilpaChandrashekara** [comment]
@ramonskie  : We have make necessary changes to the ruby version. As discussed can you please take care of vendor packing?

**Review by jpalermo — COMMENTED** [review]
Looks good to me. Thanks!

We've also got some upcoming work to change the bosh packages ruby package to make it easier to consume, similar to the golang package; and then add auto-bumping of the ruby package to the bosh director release.

**Comment by beyhan** [comment]
@jpalermo is this an approval? :-)

**Comment by jpalermo** [comment]
> @jpalermo is this an approval? :-)

Great question! It was, but now I'm not sure.

We just finished updating the ruby-package. It now has stable package names and a helper concourse task so we can setup a pipeline to just autobump the "3.1" package.

My plan was to merge this, and then add a new commit to make the changes needed to move to the new package naming convention.

~~But now that I'm looking closer at this PR, I'm confused about the additions to the `spec.lock` and `.final_builds/packages` files. How did those get uploaded to the blobstore already~~

Now I see, there were additional commits to upload the blobs.

Okay, this still seems good to me then. I think it's fine to merge this, and then I'll make a PR in the next few days or the ci pipeline files to add in the auto bumping. A lot of the versions can be changed from major.minor.patch to just major.minor and the auto bumping won't have to do as much now that the ruby-release has been restructured. But there might be some spots that still need a patch. Haven't dug in yet.

**Review by jpalermo — APPROVED** [review]

**Comment by ramonskie** [comment]
@jpalermo I added the blobs ;)

**Comment by jpalermo** [comment]
Thanks @ramonskie, is this good to be merged now? You haven't approved it, but you did make commits, so it's like 3/4 of an approval? :)

**Review by ramonskie — APPROVED** [review]

**Pull request merged**
