### PR TITLE
Enable trim mode (<% -%>) for templating

### PR DESCRIPTION
**Pull request by liuweichu**
### Issue
This PR is for https://github.com/cloudfoundry/bosh/issues/1086

### Purpose
Enable trim mode for bosh ERB templating, for more cosmetic templating output.
No backward compatibility break.

### CODE REVIEW

**Comment by liuweichu** [comment]
Individual CLA sent.
Also `Rakutentech` have signed Corporate CLA.

**Comment by cppforlife** [comment]
Can you please add a unit test for this change.

**Comment by liuweichu** [comment]
@cppforlife Hi, test case updated.

**Comment by cppforlife** [comment]
Story: https://www.pivotaltracker.com/story/show/115721889

**Comment by cunnie** [comment]
Merged: https://github.com/cloudfoundry/bosh/commit/3a161c273ed6fe5533a71e33a06e89dd7bf2c8ae

Thank you, liuweichu!

**Pull request closed without merging**
