### PR TITLE
`bosh shell-completion` generates scripts to auto complete BOSH Commands

### PR DESCRIPTION
**Pull request by dpb587-pivotal**
Signed-off-by: Jay Guo <guojiannan@cn.ibm.com>
Signed-off-by: Brian Cunnie <bcunnie@pivotal.io>

### CODE REVIEW

**Comment by dpb587-pivotal** [comment]
Closing - hopefully superceded and cleaned up by other efforts.

**Comment by allomov** [comment]
Could you tell what plans do you have on supporting autocomplete in bosh_cli?

**Comment by allomov** [comment]
I found [an old chunk of bosh code](https://github.com/cloudfoundry/bosh/blob/master/bosh_cli/lib/cli/commands/complete.rb) that seems to implement bash completion, still can't see how I can use it.

**Comment by dpb587-pivotal** [comment]
Not sure what specific plans there are for autocompletion, but I think there will be some refactoring and I'd rather not try to keep the PR up to date with those efforts. If you're interested, you could try manually applying the [pr patch](https://patch-diff.githubusercontent.com/raw/cloudfoundry/bosh/pull/1074.patch) locally and review the `bosh shell-completion` output for instructions on how to use it

I hadn't seen that old chunk of bosh code referencing completion before - not sure how to use it or if it's still useful code.

**Pull request closed without merging**
