### PR TITLE
fix: src/Gemfile to reduce vulnerabilities

### PR DESCRIPTION
**Pull request by nikhen**
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-RUBY-EXCON-537866
- https://snyk.io/vuln/SNYK-RUBY-RACK-538324
- https://snyk.io/vuln/SNYK-RUBY-RACKPROTECTION-20394
- https://snyk.io/vuln/SNYK-RUBY-SINATRA-20488
- https://snyk.io/vuln/SNYK-RUBY-SINATRA-22027

### What is this change about?

_Describe the change and why it's needed._

### Please provide contextual information.

_Include any links to other PRs, stories, slack discussions, etc... that will help establish context._

### What tests have you run against this PR?

_Include a comprehensive list of all tests run successfully._

### How should this change be described in bosh release notes?

_Something brief that conveys the change and is written with the Operator audience in mind.
See [previous release notes](https://github.com/cloudfoundry/bosh/releases) for examples._

### Does this PR introduce a breaking change?

_Does this introduce changes that would require operators to take care in order to upgrade without a failure?_

### Tag your pair, your PM, and/or team!
_It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._

### CODE REVIEW

**Comment by h4xnoodle** [comment]
hello @nikhen have you tested these upgrades at all before filing the PR? What is the risk associated with merging?

Thanks,
Rebecca, BOSH [Pivotal/VMWare]

**Comment by nikhen** [comment]
Hi, @h4xnoodle , thanks for considering this PR. I tested this to my best knowledge. I could not find any issues. This PR raises the version of some dependencies. There are no side-effects to my knowledge, but then you never know. Is there a policy on versions in dependencies?
Are there further guidelines on testing which I should take into consideration in addition to testing to my best knowledge? Please do not hesitate to post further requirements here.
Thanks/regards,
nikolaus

**Comment by h4xnoodle** [comment]
Thanks for following up. I assume your testing included running the unit tests -- is that right?

Unit tests is enough for a PR in most cases. We have CI pipelines that will run through integration and release acceptance tests. Integration tests are generally runnable locally/by PR submitters. I'll merge this now, but if there are issues then I will follow up.

Thanks!

**Comment by nikhen** [comment]
ok, thanks, let's proceed as you suggest. As soon as there are issues, please do not spend time analyzing, but send the error message to me and I take a look.

**Comment by h4xnoodle** [comment]
Merging this immediate caused a lot of red for us. Running `bundle install` shows that there is a locked sinatra. Did you get the same problem on your end when testing? Did you run the unit tests with `bundle exec rake spec:unit` from `bosh/src`?

**Comment by nikhen** [comment]
This PR was created using a preliminary version of the snyk pull request feature which seems to introduce unwanted side-effects.

I will look into this and update the PR accordingly. I cannot add a label to this PR, but please consider this inactive until I have looked into the issue and updated the PR.

Thanks/regards,
nikolaus

**Comment by h4xnoodle** [comment]
I've already gone and updated the nested gems. In general, the automated PRs generated never work well for this project. They are used as a guide. For any PR, a great litmus test is to run the unit tests first. In this case, running a `bundle` as well. 

I updated the gemspecs to sinatra 2.0.2 https://github.com/cloudfoundry/bosh/commit/3fd0ddd26cbcf6fd88887ba7644676a4adfe121b

**Comment by nikhen** [comment]
Hi @h4xnoodle, thanks for the information. I will integrate this into my workflow.
Regards, nikolaus

**Pull request merged**
