### PR TITLE
Update WALA to 2.1.3 for Azure.

### PR DESCRIPTION
**Pull request by AbelHu**

### CODE REVIEW

**Comment by cppforlife** [comment]
@AbelHu what's in the update? why do we need to bump?

**Comment by AbelHu** [comment]
@cppforlife New WALA supports new protocols on Azure. It also supports AzureStack.

**Comment by cppforlife** [comment]
Does that mean older stemcells will stop working because they dont support newer protocol?

**Comment by AbelHu** [comment]
The old stemcell still works now but in future it can not work after the protocols are switched.

Best Regards,
Abel HU

? 2016?3?3??08:59?Dmitriy Kalinin <notifications@github.com<mailto:notifications@github.com>> ???


Does that mean older stemcells will stop working because they dont support newer protocol?

-

**Comment by bosh-ci-push-pull** [comment]
Do you have the timeline when protocol may change?

**Comment by AbelHu** [comment]
@cppforlife Azure still supports the old protocols in future. But AzureStack only supports new protocols. In order to use the same stemcell both on Azure and AzureStack, we need to update WALA to 2.1.3.

**Comment by cppforlife** [comment]
Got it. Story: https://www.pivotaltracker.com/story/show/115712317

**Pull request merged**
