### PR TITLE
Enable coverage report generation when running unit tests on ci

### PR DESCRIPTION
**Pull request by rkoster**
### What is this change about?

This PR restores simplecov code coverage reporting when running unit tests in ci.
In the past, this must have worked because the required configuration is [already in place](https://github.com/cloudfoundry/bosh/blob/main/src/spec/shared/spec_helper.rb#L3-L18), however, the simpelcov gem itself was no longer included in the Gemfile.

### Please provide contextual information.

At VMware we have an internal ask to report test coverage for components we ship, also from an OSS point of view knowing our test coverage is a best practise. 

### What tests have you run against this PR?

Have tested locally using:
```
docker run \
       --mount type=bind,source="$(pwd)",target=/workspace/bosh-src \
       --workdir /workspace \
       --env DB=sqlite \
       --env RUBY_VERSION=3.2.0 \
       --env COVERAGE=true \
       bosh/integration bosh-src/ci/tasks/test-unit.sh
```
Which matches the [test-unit.yml ](https://github.com/cloudfoundry/bosh/blob/main/ci/tasks/test-unit.yml)task invocation

### CODE REVIEW

**Review by aramprice — APPROVED** [review]
✅ lgtm

**Comment by aramprice** [comment]
🤔 is anyone consuming this coverage output? 

If not is it worth adding this code, configuration, and run-time back in?

**Comment by ragaskar** [comment]
Didn't clone + test but LGTM.

**Review by ragaskar — APPROVED** [review]

**Comment by jpalermo** [comment]
Adding some new gems, maybe now is a good time to enable git lfs for the vendor folder

**Comment by rkoster** [comment]
> Adding some new gems, maybe now is a good time to enable git lfs for the vendor folder

Done: https://github.com/cloudfoundry/bosh/pull/2439/commits/dac1f51d92d0015bc6e23c6c06c50b251e09513c

**Pull request merged**
