### PR TITLE
Json plugin manages processes

### PR DESCRIPTION
**Pull request by wfernandes**
If a json plugin compatible process dies, the json plugin will restart it. Also, jobs appearing in the manifest after the health_monitor will be detected and started.

### CODE REVIEW

**Comment by joerodriguez** [comment]
@cppforlife This is the work that you had suggested during our conversation at CF Summit.

**Comment by wfernandes** [comment]
@cppforlife Just wanted an update on this PR. We'd like to get this in as soon as possible as it is vital for the smooth operation of the bosh-system-metrics-server. Thanks.

**Comment by zachgersh** [comment]
@wfernandes would it be possible to write an integration test for this? Would be really nice if we could go build a plugin that would be started / receive and maybe echo the events?

Just a quick glance first idea.

**Comment by jtarchie** [comment]
@zachgersh, we'd love to. We've had some troubles with testing multiple loops with EventMachine (ie we don't know how to). Is anyone available to pair on it next week?

**Comment by cppforlife** [comment]
@jtarchie 

> Is anyone available to pair on it next week?
yup, reach out to us next week and we'll pair

**Comment by tjvman** [comment]
Confirmed that new behavior works with manual testing; integration and unit tests are passing locally.

**Pull request merged**
