### PR TITLE
Provide better error message in case of disabled cloud-config

### PR DESCRIPTION
**Pull request by domdom82**
Fixes issue #1604 

Trying to provide a better error message that hints to missing cloud-config in director.

### CODE REVIEW

**Comment by tjvman** [comment]
@domdom82 Thanks for the PR! "with cloud config enabled on your director" still feels a bit misleading because the issue isn't one of enablement (there's no property for cloud configs) but rather that no cloud config has been uploaded. What would you think of tweaking it to "with a cloud config uploaded to your director" or something similar?

**Comment by jaresty** [comment]
merge story [#152973162](https://www.pivotaltracker.com/story/show/152973162)

**Comment by jfmyers9** [comment]
Closing and reopening so that gitbot makes a story.

**Comment by miguelverissimo** [comment]
This was merged and later reverted since it breaks the integration tests

**Comment by freddesbiens** [comment]
This has been fixed and will appear in our next release. The revised error message is: 

`Error: Deployment manifest contains 'stemcells' section, but it can only be used with cloud-config enabled on your bosh director.`

Thank you for your patience!

**Comment by domdom82** [comment]
yaay!

**Pull request merged**
