### PR TITLE
AWS Enhanced Networking Support

### PR DESCRIPTION
**Pull request by dpb587**
This PR enables the [Enhanced Networking](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html) functionality for AWS HVM VPC instances. Technically, it upgrades the `ixgbevf` kernel module from the default installed version (2.12.1-k) to 2.16.1. It also changes the light stemcell builder to register the HVM images with the correct SR-IOV flag on AWS. Discussion about this was originally started on [cf-bosh](http://lists.cloudfoundry.org/pipermail/cf-bosh/2015-June/000354.html) (thank you for the very helpful pointers).

I have deployed this PR stemcell to a couple VMs in a couple different, smaller deployments without any problems and will switch over a few more over the next few days assuming no complications. I'll followup here with any new results from those tests.

In the meantime, I thought I'd submit the PR to at least get some feedback about the implementation. A few discussion points to get this started...

0. Where should I commit/store/canonicalize the upstream ixgbevf-2.16.1.tar.gz? It's currently being downloaded and checksummed by `apply.sh`. I wasn't quite sure what "vendored source" meant in the mailing list reply and I didn't see a similar use case that I could follow as an example.
0. I created it from an ubuntu-specific perspective, even though it might work for others. It's just the only setup I have experience with and am able to confidently test in my environments. Thoughts?
0. What does your testing process usually look like for integrating stemcell changes like this, and what should the next steps be assuming the diff looks relatively sane?
0. So far, my experience with kernel-related stuff, and BOSH stemcells in particular, is extremely limited. Please let me know what else I can learn to improve this PR.

I went through the following process to build/verify. In summary I tested upgrading an existing VM from a bosh.io stemcell and verified it still worked when running this PR stemcell. For paravirtual, I verified it contained the updated kernel module, but that the image was not marked as SR-IOV. For HVM, verified it had the updated kernel module and was marked as SR-IOV. And obviously in both cases that networking was fully functional and the jobs running.

 * `build_os_image`
 * `build_with_local_os_image`
 * `build_light[...tgz,pv]`
    * `virtualization` => **`pv`**
    * `ami` => `ami-6c7e3a1b`
    * `sriovNetSupport` => `{}`
    * existing VM (i-f8d25552)
       * `instanceType` => `c3.large`
       * `ami` => `ami-25205a52` (bosh-aws-xen-ubuntu-trusty-go_agent/2992)
       * `ixgbevf` => **`2.12.1-k`**
       * `sriovNetSupport` => **`{}`**
    * redeployed with PR stemcell (i-d5e4637f)
       * `ami` => `ami-6c7e3a1b`
       * `ixgbevf` => **`2.16.1`**
       * `sriovNetSupport` => **`{}`**
 * `build_light[...tgz,hvm]`
    * `virtualization` => **`hvm`**
    * `ami` => `ami-c07f3bb7`
    * `sriovNetSupport` => `{ "Value": "simple" }`
    * existing VM (i-4a76cce0)
       * `instanceType` => `m3.large`
       * `ami` => `ami-65275d12` (bosh-aws-xen-hvm-ubuntu-trusty-go_agent/2992)
       * `ixgbevf` => **`2.12.1-k`**
       * `sriovNetSupport` => **`{}`**
    * redeployed with PR stemcell (i-8ff67125)
       * `ami` => `ami-c07f3bb7`
       * `ixgbevf` => **`2.16.1`**
       * `sriovNetSupport` => **`{ "Value": "simple" }`**

I was using the following commands to extract the above values...

    local$ aws ec2 describe-image-attribute --image-id ami_id --attribute sriovNetSupport
    local$ aws ec2 describe-instances --instance-id instance_id
    local$ aws ec2 describe-instance-attribute --instance-id instance_id --attribute sriovNetSupport
       vm$ modinfo ixgbevf

Pre-PR, the module looks like...

    filename:       /lib/modules/3.16.0-41-generic/kernel/drivers/net/ethernet/intel/ixgbevf/ixgbevf.ko
    version:        2.12.1-k
    license:        GPL
    description:    Intel(R) 10 Gigabit Virtual Function Network Driver
    author:         Intel Corporation, <linux.nics@intel.com>
    srcversion:     C02B691BD236020418674D0
    alias:          pci:v00008086d00001515sv*sd*bc*sc*i*
    alias:          pci:v00008086d000010EDsv*sd*bc*sc*i*
    depends:        
    intree:         Y
    vermagic:       3.16.0-41-generic SMP mod_unload modversions 
    signer:         Magrathea: Glacier signing key
    sig_key:        42:AE:B7:DF:54:E6:D9:1C:A0:F4:01:21:E2:2F:EA:E6:B2:30:88:16
    sig_hashalgo:   sha512
    parm:           debug:Debug level (0=none,...,16=all) (int)

With PR, the module looks like...

    filename:       /lib/modules/3.16.0-41-generic/updates/dkms/ixgbevf.ko
    version:        2.16.1
    license:        GPL
    description:    Intel(R) 10 Gigabit Virtual Function Network Driver
    author:         Intel Corporation, <linux.nics@intel.com>
    srcversion:     3B690FE23A02C25EF74012F
    alias:          pci:v00008086d00001515sv*sd*bc*sc*i*
    alias:          pci:v00008086d000010EDsv*sd*bc*sc*i*
    depends:        
    vermagic:       3.16.0-41-generic SMP mod_unload modversions 
    parm:           InterruptThrottleRate:Maximum interrupts per second, per vector, (956-488281, 0=off, 1=dynamic), default 1 (array of int)

### CODE REVIEW

**Comment by cppforlife** [comment]
Awesome PR! 

By vendor I mean we will actually include the source tarball for ixgbevf when pulling in this PR. 

One thing I noticed is that sriov flag is set for all AWS stemcells, which means it will be included for CentOS. Do you happen to know if this work for CentOS stemcells?

**Comment by cppforlife** [comment]
Also it appears that we do not have a CLA for you.

**Comment by mrdavidlaing** [comment]
@cppforlife - @dpb587 is doing this work on behalf of City Index (https://github.com/cityindex/), who you should have a Corporate CLA from.  Please send an email to david.laing@cityindex.com if you don't; and I'll dig out the paperwork and resubmit.  Thanks

**Comment by mrdavidlaing** [comment]
@dpb587 Just out of interest, in your testing is it possible to capture any data about the improvements in network performance that this brings?

**Comment by dpb587** [comment]
Okay, so it's safe to just commit the tgz into the assets directory then? It was only ~100 KB.

In theory the SR-IOV would be supported on CentOS images, as far as AWS is concerned. But it wasn't my intention to make it a global AWS setting since I'm only able to test and verify the Ubuntu images, and since I only added the newer ixgbevf onto Ubuntu . Is there a way to make it only an Ubuntu flag until somebody familiar with CentOS is able to look into adding/testing the support?

In regards to CLA, @mrdavidlaing commented; should be on file somewhere.

In regards to Travis saying test failures, I didn't realize there were more tests than already ran during build steps. I'll take a closer look at what it's doing and see if there's things I can fix.

@mrdavidlaing, the deployments I'm testing this on don't really have enough detailed monitors for network performance to be able to add a fancy comparison here. And we don't really have a test focused on this area. So for now, I'd just trust results that other companies publish which are dedicated to comparing AWS SR-IOV vs not.

**Comment by cppforlife** [comment]
Yeah, including tgz is fine.

There are some units tests around the bosh-stemcell & stemcell_builder mostly for stemcell building code itself.

**Comment by dpb587** [comment]
Branch Update - On Monday I rebased and recreated stemcells.

Usage Update - I've continued using and deploying the Ubuntu Trusty HVM w/ SR-IOV and haven't run into any issues.

CentOS Update - Tuesday I built CentOS stemcells with SR-IOV enabled on HVM, I manually ran an instance off the HVM and PV images, verifying network connectivity. So, I can now at least confirm they remain functional with these changes, but that's the extent I'm able to work on and test CentOS-related stuff. CentOS HVM uses the default-installed `ixgbevf` module:

    $ modinfo ixgbevf
    filename:       /lib/modules/3.10.0-229.7.2.el7.x86_64/kernel/drivers/net/ethernet/intel/ixgbevf/ixgbevf.ko
    version:        2.12.1-k
    license:        GPL
    description:    Intel(R) 10 Gigabit Virtual Function Network Driver
    author:         Intel Corporation, <linux.nics@intel.com>
    rhelversion:    7.1
    srcversion:     8A486FF1F6EC9EAE0E85E18
    alias:          pci:v00008086d00001515sv*sd*bc*sc*i*
    alias:          pci:v00008086d000010EDsv*sd*bc*sc*i*
    depends:        
    intree:         Y
    vermagic:       3.10.0-229.7.2.el7.x86_64 SMP mod_unload modversions 
    signer:         CentOS Linux kernel signing key
    sig_key:        0C:69:17:57:20:AA:08:13:53:85:A8:AC:54:7B:0E:37:75:26:ED:64
    sig_hashalgo:   sha256
    parm:           debug:Debug level (0=none,...,16=all) (int)

The following are the manually crafted lights referencing the public images for the regions, if anybody notices this PR and would like to test them out, pre-merge:

 * [bosh-aws-xen-hvm-ubuntu-trusty-go_agent/sriov20150630a](https://ci-logsearch.s3.amazonaws.com/bosh-stemcell/aws/light-bosh-stemcell-sriov20150630a-aws-xen-hvm-ubuntu-trusty-go_agent.tgz)
 * [bosh-aws-xen-ubuntu-trusty-go_agent/sriov20150630a](https://ci-logsearch.s3.amazonaws.com/bosh-stemcell/aws/light-bosh-stemcell-sriov20150630a-aws-xen-ubuntu-trusty-go_agent.tgz)
 * [bosh-aws-xen-hvm-centos-7-go_agent/sriov20150630a](https://ci-logsearch.s3.amazonaws.com/bosh-stemcell/aws/light-bosh-stemcell-sriov20150630a-aws-xen-hvm-centos-7-go_agent.tgz)
 * [bosh-aws-xen-centos-7-go_agent/sriov20150630a](https://ci-logsearch.s3.amazonaws.com/bosh-stemcell/aws/light-bosh-stemcell-sriov20150630a-aws-xen-centos-7-go_agent.tgz)

At this point, I don't have any further changes to make here. If there's anything else you need from me to move this PR forward, please let me know (although I now see the *ready-to-pull-in* label now - hooray!).

**Comment by cppforlife** [comment]
Thanks for the additional testing! Nothing else to do for you. We will pull it in soon.

**Comment by cppforlife** [comment]
Thank you for the excellent PR! It has been included in the few previous stemcells.

**Pull request closed without merging**
