### PR TITLE
When adding a new tombstone record, delete all the older ones

### PR DESCRIPTION
**Pull request by jpalermo**
Noticed that these are never cleaned up currently. There may be a performance hit when the first new tombstone record is added and thousands of old ones are destroyed but it shouldn't be terrible.

### CODE REVIEW

**Review by aramprice — APPROVED** [review]
lgtm

**Review by selzoc — APPROVED** [review]

**Comment by beyhan** [comment]
cool finding! 👍

**Comment by aramprice** [comment]
This PR seems to be causing consistent `Deadlock` errors in the MySQL [integration specs](https://bosh.ci.cloudfoundry.org/teams/main/pipelines/bosh-director/jobs/integration-db-tls-mysql/builds/220#L66749ca0:3713).

Reformatted output from CI job above
```
bosh  --tty -n -e https://127.0.0.1:61702 -d simple \
--config /tmp/build/04d13fd0/bosh-src/src/tmp/integration-tests-workspace/pid-16878/client-sandbox/bosh_config.yml \
--ca-cert /tmp/build/04d13fd0/bosh-src/src/bosh-dev/assets/sandbox/ca/certs/rootCA.pem delete-deployment 

Using environment 'https://127.0.0.1:61702' as client 'production_team'

Using deployment 'simple'

Task 4

Task 4 | 03:19:29 | Deleting instances: fake-name1/a977324b-4e5a-4cbb-97ee-cc76fcd736f7 (0)
Task 4 | 03:19:29 | Deleting instances: fake-name1/479efb85-a860-4d4a-855a-db0f7fa40c40 (2)
Task 4 | 03:19:29 | Deleting instances: fake-name1/6ad77256-ae09-4650-8297-4516716d4a2a (1)
Task 4 | 03:19:31 | Deleting instances: fake-name1/479efb85-a860-4d4a-855a-db0f7fa40c40 (2) (00:00:02)
Task 4 | 03:19:31 | Deleting instances: fake-name1/6ad77256-ae09-4650-8297-4516716d4a2a (1) (00:00:02)
                  L Error: Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction
Task 4 | 03:19:31 | Deleting instances: fake-name1/a977324b-4e5a-4cbb-97ee-cc76fcd736f7 (0) (00:00:02)
Task 4 | 03:19:31 | Error: Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction

Task 4 Started  Sun Jun 30 03:19:29 UTC 2024
Task 4 Finished Sun Jun 30 03:19:31 UTC 2024
Task 4 Duration 00:00:02
Task 4 error

Deleting deployment 'simple':
  Expected task '4' to succeed but state is 'error'

Exit code 1
```

**Comment by beyhan** [comment]
@aramprice @jpalermo should we open an issue for the above mentioned deadlocks or it is addressed already?

**Comment by jpalermo** [comment]
New [PR](https://github.com/cloudfoundry/bosh/pull/2536) to move it to a scheduled job

**Comment by beyhan** [comment]
Thanks! @jpalermo this was faster than the light :-)

**Comment by jpalermo** [comment]
Convenient timing 😀

**Pull request merged**
