### PR TITLE
Remove PowerDNS

### PR DESCRIPTION
**Pull request by aramprice**
### What is this change about?

Remove PowerDNS

### Please provide contextual information.

The PowerDNS package has not been updated since 2016. This commit removes:
- package
- job
- all config values under `dns` except `domain_name`
- models under `src/bosh-director/lib/bosh/director/models/dns/`
  - all mention or use of `dns_db` which was a separate database configuration for these models

### What tests have you run against this PR?

✅ `rake fly:unit`
✅ `rake fly:integration`
✅ `DB=mysql rake fly:integration`

### How should this change be described in bosh release notes?

PowerDNS job and associated code is removed.

### Does this PR introduce a breaking change?

Yes, operators who use PowerDNS will need to migrate to an alternative before upgrading to this release.

----

- PR to remove `bosh-deployment`'s [misc/powerdns.yml](https://github.com/cloudfoundry/bosh-deployment/blob/master/misc/powerdns.yml)
  - https://github.com/cloudfoundry/bosh-deployment/pull/459
- PR to remove PowerDNS from `docs-bosh`
  - https://github.com/cloudfoundry/docs-bosh/pull/829
- PR to remove `--dns` flag and functionality from `bosh` CLI
  - https://github.com/cloudfoundry/bosh-cli/pull/644
- PR to remove usage in Openstack CPI
  - https://github.com/cloudfoundry/bosh-openstack-cpi-release/pull/270

### CODE REVIEW

**Review by lnguyen — APPROVED** [review]
LGTM

**Comment by aramprice** [comment]
Question from https://github.com/cloudfoundry/bosh-cli/pull/644#discussion_r1535886899
> What happens when a director w/o PowerDNS receives a `--dns` flag on the `instances` or `vms` command?

cc @ystros

**Comment by aramprice** [comment]
> Question from [cloudfoundry/bosh-cli#644 (comment)](https://github.com/cloudfoundry/bosh-cli/pull/644#discussion_r1535886899)
> 
> > What happens when a director w/o PowerDNS receives a `--dns` flag on the `instances` or `vms` command?
> 
> cc @ystros

The director code returning a `dns` response currently _always_ returns this field in the JSON, however it is only ever populated PowerDNS is enabled. see [bosh-director/lib/bosh/director/jobs/vm_state.rb:49-56](https://github.com/cloudfoundry/bosh/blob/main/src/bosh-director/lib/bosh/director/jobs/vm_state.rb#L49-L56)

**Comment by beyhan** [comment]
Let's wait for another approval on this because the change is quite large.

**Review by danielfor — APPROVED** [review]
LGTM

**Pull request merged**
