### PR TITLE
Allow custom syslog rule for forwarding

### PR DESCRIPTION
**Pull request by ronakbanka**
This PR will add option to add any optional forwarding rules .

### CODE REVIEW

**Comment by voelzmo** [comment]
Hey @ronakbanka thanks for the PR. Out of curiosity: What is it that you want to forward but isn't covered by the current settings?

**Comment by ronakbanka** [comment]
@voelzmo : We are using omkafka package to forward syslog stream to Kafka brokers , so instead of setting a syslog endpoint we add the custom rule with configuration.
Reference: http://www.rsyslog.com/doc/master/configuration/modules/omkafka.html

**Comment by cppforlife** [comment]
https://www.pivotaltracker.com/story/show/113476343

**Comment by rnandi** [comment]
Merged in cb7cead3d3b29654e93945989eeedcb6ecf17301 on develop

All active development on BOSH happens on develop, and all pull requests are merged into develop as well. Master on BOSH is representative of the latest bosh-release that is on bosh.io. In the future, please submit pull requests to the develop branch instead of master.

Thanks for the pull request!

**Pull request closed without merging**
