### PR TITLE
Initial riemann plugin

### PR DESCRIPTION
**Pull request by sharms**
- Add colon
 - Tag service
 - Add Riemann options to release.
 - Add tests for Riemann plugin.
 - Install Riemann client.
 - Fix typos.
 - Use top-level Riemann client.
 - Use or-equals operator.
 - Flatten event details and set state.
 - Handle heartbeat and alert separately.
 - Check in vendored dependencies.
 - Update health monitor manifest tests.

Conflicts:
	Gemfile.lock

### CODE REVIEW

**Comment by sharms** [comment]
Opened against develop as noted in #1337

**Comment by dpb587-pivotal** [comment]
Helpful - thanks!

+1 from me, and vendor gems are verified.

**Comment by dpb587-pivotal** [comment]
Merged - thanks!

**Comment by jmcarp** [comment]
@dpb587: when do you think this might make it into an official release?

**Comment by dpb587-pivotal** [comment]
@jmcarp: unfortunately I'm not sure. I'm hoping we can release from develop sooner rather than later, but some other priorities and fixes for previous releases and stemcells have been taking precedence lately.

For the short-term, you might need to manually pull in this [PR's patch](https://patch-diff.githubusercontent.com/raw/cloudfoundry/bosh/pull/1351.patch) on your director, or build a local release from it.

**Pull request merged**
