### PR TITLE
Use FactoryBot to create DeploymentPlan Factories

### PR DESCRIPTION
**Pull request by charleshansen**
### What is this change about?

Create Factories for deployment plan objects in test

### Please provide contextual information.

Tests that require DeplymentPlan objects can have hundreds of lines of setup just to create the objects, we should use factories. Machinist won't work with DeploymentPlan objects, but FactoryBot does (because of initialize_with). To discuss further perhaps in tech retro.

### What tests have you run against this PR?

Unit tests pass

### How should this change be described in bosh release notes?

Testing change only, no notes

### Does this PR introduce a breaking change?

No

### CODE REVIEW

**Comment by mrosecrance** [comment]
Didn't you already merge this in? Can we delete the pr?

**Comment by jfmyers9** [comment]
Yep this change appears to already exist on the master branch. Going to close this PR.

**Comment by jfmyers9** [comment]
@charleshansen Can you delete the branch if it is no longer in use?

**Comment by charleshansen** [comment]
Actually still using the branch, but good to close the PR

**Pull request closed without merging**
