### PR TITLE
add NM_CONTROLLED=no to Azure network script

### PR DESCRIPTION
**Pull request by gossion**
Fixes the issue that Azure CentOS VM can't be created when it has multiple dynamic NICs.

### CODE REVIEW

**Comment by gossion** [comment]
Hi @cppforlife, can you help to merge this PR? it is for Azure multiple network interfaces.

**Comment by dpb587-pivotal** [comment]
@ljfranklin, @cunnie: any reason we shouldn't be merging this?

**Comment by ljfranklin** [comment]
@dpb587-pivotal at a quick glance, @cunnie doesn't think this would cause any issues. However, he hedged his bets by saying he "could be wrong" :)

**Comment by gossion** [comment]
Hi @ljfranklin  and @cunnie, we found the issue on Azure and the fix is only on Azure. See more detail in [link](https://github.com/Azure/WALinuxAgent/issues/190#issuecomment-226463211).

**Comment by AbelHu** [comment]
@gossion Could you update your PR for the conflicts?

**Comment by AbelHu** [comment]
@ljfranklin This will cause the VM cannot be provisioned successfully when multiple NICs are enabled on Azure. It will cause the BATs failure. Please see below logs. It is a **block** issue when we are enabling BATs against centos stemcell in Azure CPI pipeline.

```
Failures:

  1) network configuration when using manual networking deploys multiple manual networks
     Failure/Error: expect(bosh('deploy')).to succeed
     Bosh::Exec::Error:
       command 'bundle exec bosh --non-interactive -P 1 --config /tmp/bosh_config20170221-362-1h9q7to --user azureuser --password Binxia5537 deploy --no-redact 2>&1' failed with exit code 1
     # ./lib/bat/bosh_runner.rb:19:in `bosh'
     # ./lib/bat/bosh_helper.rb:14:in `bosh'
     # ./spec/system/network_configuration_spec.rb:79:in `block (3 levels) in <top (required)>'

Finished in 247 minutes 56 seconds (files took 0.21033 seconds to load)
82 examples, 1 failure, 1 pending
```

**Comment by ljfranklin** [comment]
cc @zaksoup, new CPI team anchor

**Comment by dpb587-pivotal** [comment]
Closing - stemcell-related code has moved to [cloudfoundry/bosh-linux-stemcell-build](https://github.com/cloudfoundry/bosh-linux-stemcell-builder). Feel free to fix the mentioned multiple NICs issue and submit a new pull request there when ready.

**Pull request closed without merging**
