### PR TITLE
lets you require director client only without cli

### PR DESCRIPTION
**Pull request by bonzofenix**
Hi Bosh team,
I was trying to use `cli/client/director` without requiring all dependencies in the [cli](https://github.com/cloudfoundry/bosh/blob/master/bosh_cli/lib/cli.rb).
This speeds up loading when the goal is only to use the director client.

### CODE REVIEW

**Comment by cppforlife** [comment]
I would recommend not using it directly, but if you must to make this more maintainable https://github.com/bonzofenix/bosh/blob/master/bosh_cli/lib/cli/errors.rb should be changed to define 

```
module Bosh
  module Cli
```

instead of adding `module Bosh; end` to this file.

**Comment by bonzofenix** [comment]
@cppforlife I changed the commit. 
Why you would not recommend using only the director class only?
Thanks

**Comment by cppforlife** [comment]
Because it's a private implementation detail and can change at any time - not an official API.

**Comment by cppforlife** [comment]
Merged.

**Pull request closed without merging**
