### PR TITLE
Enable pure IPv6 Director/UAA/Credhub integration without use of DNS

### PR DESCRIPTION
**Pull request by cppforlife**
Previous iteration: https://github.com/cloudfoundry/bosh/pull/1948

Rebased onto master on Jun 4.

Building: https://main.bosh-ci.cf-app.com/teams/main/pipelines/ipv6

### CODE REVIEW

**Comment by tjvman** [comment]
@cppforlife If this is the now-canonical implementation of this behavior, would you mind closing the previous PR?

**Comment by dpb587-pivotal** [comment]
Closed the last PR. In the future, please keep pull requests open and push your changes to the existing branch rather than creating duplicate PRs in order to ease discussion and tracking. If you want to retain history prior to rebases, feel free to keep local branches or branches in your fork to avoid cluttering branch lists.

**Comment by jfmyers9** [comment]
Closing and reopening to generate a tracker story.

**Comment by mrosecrance** [comment]
We've manually merged the PR. We found that with newer versions some of the changes in here were no longer necessary, so we omitted a few of the commits in this PR. Thanks.

**Pull request closed without merging**
