### PR TITLE
Fix bosh backup scripts for external DBs

### PR DESCRIPTION
**Pull request by aclevername**
### What is this change about?

Changing the bosh directors backup script to produce an empty artifact when configured with an external DB

### Please provide contextual information.

When you configure your bosh director to use an external DB and attempt to backup using [bbr](https://github.com/cloudfoundry-incubator/bosh-backup-and-restore) it would produce an artifact that was invalid. This is due to the ruby gem used to create the backup artifact does not support external DB's, only internal. If you tried to restore with this artifact it would `succeed` falsely, leaving the director in a bad state. To negate this we want it to produce an empty backup artifact instead and for restore to no-op when configured with an external DB.

Story that discovered this issue: https://www.pivotaltracker.com/story/show/161379117
Story to fix this issue: https://www.pivotaltracker.com/story/show/162088113

### What tests have you run against this PR?

Manual testing with the following configuration:
`director.db.host` set to `localhost` - resulted in backup script being correctly templated
`director.db.host` set to `127.0.0.1` - resulted in backup script being correctly templated
`director.db.host` set to `<exteranl-db>` - resulted in backup script being templated empty (as desired)

### How should this change be described in bosh release notes?

Bug Fix- BOSH Director backup no longer produces an artifact when configured with an external DB

### Does this PR introduce a breaking change?

No

### Tag your pair, your PM, and/or team!
@gmrodgers

### CODE REVIEW

**Comment by aclevername** [comment]
Still attempting to test when the internal db is configured with `::1`, see here https://pivotal.slack.com/archives/C3M0B3TV3/p1547134391134800

Please do not merge yet.

**Comment by aclevername** [comment]
A issue has been opened regarding the inability to configure `::1` here: https://github.com/cloudfoundry/bosh/issues/2113

**Comment by aclevername** [comment]
After talking to the BOSH team we are happy that it will work correctly for `::1`.

**Comment by gmrodgers** [comment]
Hi @dpb587-pivotal 
### How do you see BBR users dealing with configuring database backups?
Not quite sure about this question.  The current external database backups produced by the restore script in this version are invalid and will restore the director to an unhealthy state when used. We would like to remove this attempt to backup external databases as it was not promised by `bbr` until the BBR SDK was introduced in BOSH v267.2.  External databases would have to be backed up outside of `bbr`.

### Should they need to know to differentiate between internal and external databases?
Yes as the internal database is backed up using `bbr` but the external was never backed up for this version we are PRing into.

### Should they be expected to add `bbr-database-X` backup jobs if they're using an external database? How does that get communicated?
The external database backup feature was never promised or communicated to the consumer of the BOSH release until the usage of the BBR SDK release in BOSH v267.2.  If we were to communicate this, we believe something similar to [this matrix](https://docs.pivotal.io/pivotalcf/2-3/customizing/backup-restore/backup-pcf-bbr.html#-external-storage-support-across-pcf-versions) would be useful.  We believe that they would have to backup the external database outside of using `bbr` and therefore not create a new `bbr-database-X` job

### Should the backup/restore functionality instead be removed from director and into the database-specific jobs which provide the local postgres database?
Not sure about this question either with regards to the PR.  This is up to the BOSH team as `bbr` will run the `backup` and `restore` scripts if they are found in the `bin/bbr/` directory of any job so the functionality should be similar if you decide to implement this.  The fix would be good regardless we are giving a false impression to the consumers of BOSH that we back up external databases for this version.

### Should the current director backup/restore functionality be fixed to work for both local and remote databases?
No as this is not a fix for backing up external databases but a fix to stop it looking like we back up external databases.

Thanks Glen

**Comment by alamages** [comment]
Hello @dpb587-pivotal, is there any update on this?

**Comment by dpb587-pivotal** [comment]
@miguelverissimo while it would be nice to provide more awareness into what might be happening in the backup, I don't believe standard output is streamed to the client where they would see that sort of message.

cc @mfine30 @jfmyers9 for prioritizing/continuing this.

**Comment by mfine30** [comment]
@miguelverissimo @dpb587 my interpretation of reading this thread is there is some potential UX improvements we could make, but they may be challenging based on current architecture/code behavior. I'd be inclined to say we should merge this and we can improve the output if/when we get feedback that we should add more.

**Comment by dpb587-pivotal** [comment]
@mfine30 accurate summary.

**Comment by jamesjoshuahill** [comment]
Hi hi

Thank you for your comments @dpb587 and @mfine30.

@miguelverissimo we have added the `else` you suggested. This skip message will be visible in `bbr` output when the `--debug` flag is set.

Josh and @alamages

**Comment by jamesjoshuahill** [comment]
Hi @h4xnoodle 

Thank you for merging our PR. How can we track the next release of v266.x? Do you know when the next patch release is due?

Josh and @alamages

**Comment by h4xnoodle** [comment]
Hi @jamesjoshuahill, we're tracking in this story: https://www.pivotaltracker.com/story/show/163197005 and once @mfine30 can accept then we'll cut a release, and the next teams will be notified/pick it up automatically.

**Pull request merged**
